# Generated by Django 5.1.3 on 2024-12-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_booking_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='booked_seats',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.AddField(
            model_name='eventdate',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
