# Generated by Django 5.1.3 on 2024-12-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_booked_seats_remove_event_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(null=True),
        ),
    ]
