# Generated by Django 5.1.3 on 2024-12-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_description_de_event_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text_de',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text_en',
        ),
    ]
