# Generated by Django 5.1.3 on 2024-12-26 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_review_text_de_remove_review_text_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='unknown@example.com', help_text='Email пользователя. Используется для идентификации.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефона пользователя.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Допустимо до 15 цифр.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
