# Generated by Django 5.1.3 on 2025-01-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_review_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
