# Generated by Django 5.1.3 on 2025-01-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_booking_date_booking_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price_currency',
        ),
    ]
